### ISSUE TITLE
Update Vulnerable Dependency

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/Zoom#13]
As per github the following dependencies need to be updated and are currently vulnerable:

- requests

**Comment by berserker1** [comment]
The current version here in requirements is **2.9.1**
* Do you want it to be like **>=2.9.1**??
* I can also create a pipenv support also
* What about other dependencies should they also be like **>=[version] instead of ==[version]**

**Comment by thealphadollar** [comment]
Make it `requests>=2.20.0`

Yeah, create the pipenv environment as well.

Leave alone the other dependencies.

**Comment by berserker1** [comment]
@thealphadollar  what about this issue? stiill open
