### ISSUE TITLE
Send emails using Sendgrid, instead of Gmail

### ISSUE THREAD

**Issue by icyflame** [metakgp/Zoom#8]
You can send emails using the `metakgp.org` domain that we have registered on Sendgrid.

**Comment by DefCon-007** [comment]
Oh, I didn't know about it! @TheMousePotato  Would you like to take this up >

**Comment by themousepotato** [comment]
Cool. Currently Zoom cannot send mails through the institute wifi. @icyflame Will it get resolved? Anyway, I'm in!

**Comment by icyflame** [comment]
@TheMousePotato Institute wifi doesn't allow the SMTP port, so you can't use the Sendgrid SMTP API. But Sendgrid also has an HTTP API, which you can try using (through a python module, of course)

This problem will be solved when run from a computer that has direct internet connection. So, we won't face this on the server.

You can test using the SMTP API inside Institute using a mobile network, and when we deploy it, it will work.

**Comment by themousepotato** [comment]
@ghostwriternr Can you please provide sendgrid access token for metakgp? @icyflame I still didn't get [this](https://sendgrid.com/docs/API_Reference/Web_API/Legacy_Features/Marketing_Emails_API/sender_address.html).

**Comment by ghostwriternr** [comment]
I don't think we're even using Sendgrid? Afaik we have an account + key on mailgun.

**Comment by icyflame** [comment]
@ghostwriternr Yeah, that's what I meant. I will generate this and send this to you @TheMousePotato.

**Comment by icyflame** [comment]
Fixed in #12
